### ISSUE TITLE
Question for training

### ISSUE THREAD

**Issue by yanx27** [dragonbook/pointnet2-pytorch#1]
Hi @dragonbook ! Thank you for your work!

I would like to know 
1、Did you try to train 50 part categories together like pointnet++, instead of training separately.
2、How long does each category need to be trained.

**Comment by dragonbook** [comment]
Hi, @yanx27 

I have not trained all part categories together, you can have a try.
For training time, It takes about 1.5 hour to train on Airplane(2349 examples) class with batchsize=8 and num_epoches=25(GPU: TITIAN XP). It can be a clue about the performance.

**Comment by yanx27** [comment]
@dragonbook Thank you！When I saw your photo, I found out that we were alumni, I was a 2014 undergraduate of SYSU. hhh

**Comment by dragonbook** [comment]
Haha~
