### ISSUE TITLE
Issue for dataset.num_classes

### ISSUE THREAD

**Issue by yanx27** [dragonbook/pointnet2-pytorch#2]
Hi, recently I ran your code and found there was a hidden bug in it.  dataset.num_classes actually returned 1 more categories than the actual number of categories. Therefore when you calculate mIOU, it will lead to an extra 1, so when you average it, your result will be higher than traditional Pointnet++.

**Comment by dragonbook** [comment]
Thank you! you are right! I found this is a bug from pytorch_geometric of old versions. I upgraded the library,  the shapenet can return correct num_classes now.  The old recorded  mIOU was affected by that wrong num_classes and became much higher.
