### ISSUE TITLE
How to prepare the train and test datasets for pytorch geometric?

### ISSUE THREAD

**Issue by limt15** [dragonbook/pointnet2-pytorch#3]
Hi, thank you for sharing the code.
Could you please tell me how to prepare the train and test datasets from the point cloud dataset, like s3dis and scannet?

**Comment by dragonbook** [comment]
Hi, I'm not familiar with these datasets, but you may find some paper or code about them in this [awesome-point-cloud-analysis](https://github.com/Yochengliu/awesome-point-cloud-analysis) repo and [pytorch_geometric](https://github.com/rusty1s/pytorch_geometric) repo.
