### ISSUE TITLE
Results for all classes?

### ISSUE THREAD

**Issue by AruniRC** [dragonbook/pointnet2-pytorch#4]
Hi, the results table shows per class IoU. 
Could you please also show the overall IoU for segmentation (over all classes), so we know how close to expect our results using this codebase?

**Comment by dragonbook** [comment]
Hi, you can directly try pytorch_geometry's [pointnet2_segmentation example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_segmentation.py), it can train all classes together and show the overall IoU for segmentation by setting [category](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_segmentation.py#L13) to None in that file. The IoU should be close to this repo, you can check it by training some categories.

**Comment by AruniRC** [comment]
Thanks for the response. Training for all the categories, instead of
one-at-a-time, actually gave results a bit worse than reported in the
paper.

**Comment by dragonbook** [comment]
That should be acceptable since there exist difference between training and data augmentation.
