### ISSUE TITLE
Dependency Versions

### ISSUE THREAD

**Issue by cheng-chi** [dragonbook/pointnet2-pytorch#6]
Hi Yalong! I have been trying your implementation of PointNet++. However, it seems like the API of several libraries that this repository depends on has changed (torch-geometric etc). Could you specify the versions of these libraries that you used?

**Comment by dragonbook** [comment]
Hi, cheng-chi. I have updated the dependency versions, you can check them in README.

**Comment by cheng-chi** [comment]
Whoa that's fast! Thanks!

**Comment by dragonbook** [comment]
Besides, the basic structure of  pytorch_geometric's pointnet++ implementation is similar to here, but much clean and better(support batch samples with different number of points, keep update with library). So you could  try pytorch_geometric directly:)
